[[pages]]
path = "DataForce.py"
name = "DataForce"
icon = ":material/home:"

[[pages]]
path = "pages/0_Explorer.py"
name = "Explorer"

[[pages]]
path = "pages/1_Branches.py"
name = "Branches"

[[pages]]
path = "pages/2_Customers.py"
name = "Customers"

[[pages]]
path = "pages/3_Digital_Sessions.py"
name = "Digital Sessions"

[[pages]]
path = "pages/4_Error_Codes.py"
name = "Error Codes"

[[pages]]
path = "pages/5_Feature_Costs.py"
name = "Feature Costs"

[[pages]]
path = "pages/6_Support_Interactions.py"
name = "Support Interactions"

[[pages]]
path = "pages/Customer_Simulations.py"
name = "Customer Simulations - In Progress"
hidden = true

[[pages]]
path = "pages/About.py"
name = "About"
icon = ":material/info:"

